version: "3"
volumes:
  postgres-data:
services:
  main:
    image: proxy-app
    expose:
      - "8080"
    ports:
      - "8080:8080"
    networks:
      - default
    depends_on:
      - proxy-db
  proxy-db:
    image: postgres:latest
    expose:
      - "5432"
    volumes:
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql
    env_file:
      - ./env/db.env
    ports:
      - "5432:5432"
    restart: on-failure
